[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Re-mapping to ensure forge-std routes smoothly inside GitHub Actions
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# Sets up a public network access endpoint for the Sepolia network fork simulation
[rpc_endpoints]
sepolia = "https://ankr.com"
