[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Re-mapping to ensure forge-std routes smoothly inside GitHub Actions
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# Using your newly generated Sepolia authenticated API key
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/alch_zgx5g7ieYcNBprQeKp1Kc"
